CLOSE_COOKIE_POPUP_BUTTON = "body > div.SAN-panel.SAN-panel_context.wrapper > div > button"
FEATURED_INSIGHTS_TITLE = "body > main > div.insights.bot-scroll > div.insights__featured > h2"
WRITE_BUTTON = "body > main > div.top > div > a"
TAB = "body > main > div.SAN-tabs.tabs > a.SAN-tab"
ACTIVE_TAB = "body > main > div.SAN-tabs.tabs > a.SAN-tab.active"
LOADER = "body > div.bar > div"
DRAFT = "body > main > div.insights.bot-scroll > div"
DRAFT_DELETE_BUTTON = "div > div > svg"
DRAFT_EDIT_BUTTON = "div > div > a"
DRAFT_TITLE = "a.title"
DRAFT_BODY = "h4"
DRAFT_TIMESTAMP = "div.bottom > h3:nth-child(1)"
DRAFT_DELETE_DIALOG = "body > div.bg > div"
DRAFT_DELETE_CANCEL =  "div.SAN-dialog__actions.actions > button:nth-child(1)"
DRAFT_DELETE_CONFIRM = "div.SAN-dialog__actions.actions > button:nth-child(2)"
INSIGHT = "body > main > div.insights div.insights__item"
INSIGHT_TITLE = "div > div > div.top > a"
INSIGHT_AUTHOR = "div > div.left > div.top > div > div.info > a"
INSIGHT_TIMESTAMP = "div > div.left > div.top > div > div.info > div.status"
INSIGHT_TAG = "div > div.left > div.bottom > div:nth-child(2) > a"
INSIGHT_TAG_TITLE = "div > div.right > h3"
INSIGHT_LIKE_BUTTON = "div > div.left > div.bottom > div.bottom__left > button"
EDITOR_TITLE = "#react-mount-node > div > div.InsightEditor-module_insightWrapper__3CQqa > textarea"
EDITOR_BODY = "#react-mount-node > div > div.InsightEditor-module_insightWrapper__3CQqa > div > div > div.DraftEditor-root > div.DraftEditor-editorContainer > div > div > div > div"
EDITOR_PUBLISH_MENU_BUTTON = "#react-mount-node > div > div.InsightEditor-module_bottom__1VQ3s > div button"
EDITOR_TAG_INPUT = "div[id*='react-select-'][id$='--value'] > div.Select-input > input"
EDITOR_TAG_LIST = "div[id*='react-select-'][id$='--list']"
EDITOR_TAG_LIST_ITEM = "div[id*='react-select-'][id$='--list'] > div:nth-child(1) > div > div > div.VirtualizedSelectOption"
EDITOR_TAG_LIST_TOGGLE = "body > div.Modal-module_wrapper__3yPRh.ContextMenu-module_wrapper__NSGRk > div.Tooltip-module_tooltip__5Yj1c.ContextMenu-module_menu__3N81H > div > div.Select.Select-module_topDropdown__dOxgi.Select--multi > div > span.Select-arrow-zone > span"
EDITOR_SELECTED_TAG = "span[id*='react-select-'][id*='--value-']"
EDITOR_CLEAR_TAGS = "body > div.Modal-module_wrapper__3yPRh.ContextMenu-module_wrapper__NSGRk > div.Tooltip-module_tooltip__5Yj1c.ContextMenu-module_menu__3N81H > div > div.Select.Select-module_topDropdown__dOxgi > div > span.Select-clear-zone > span"
EDITOR_PUBLISH_INSIGHT_BUTTON = "body > div.Modal-module_wrapper__3yPRh.ContextMenu-module_wrapper__NSGRk > div.Tooltip-module_tooltip__5Yj1c.ContextMenu-module_menu__3N81H > div > button"
EDITOR_PUBLISH_INSIGHT_LOADER = "body > div.Modal-module_wrapper__3yPRh.ContextMenu-module_wrapper__NSGRk > div.Tooltip-module_tooltip__5Yj1c.ContextMenu-module_menu__3N81H > div > button > div"
EDITOR_SAVED_TIMESTAMP = "#react-mount-node > div > div.InsightEditor-module_bottom__1VQ3s > div > span"
READ_TITLE = "body > main > div.insight > h1.title"
READ_BODY = "body > main > div > div.text > p"
READ_TAG = "body > main > div > div.bottom > a"
READ_AUTHOR = "body > main > div > div.insight__info > div > div.info > a"
READ_TIMESTAMP = "body > main > div > div.insight__info > div > div.info > div"
READ_FOLLOW_BUTTON = "body > main > div > div.insight__info > button"
READ_LIKE_BUTTON = "body > main > div > div.bottom.bot-scroll > div > div:nth-child(3) > button"
READ_SHARE_BUTTON = "body > main > div > div.bottom.bot-scroll > div > div:nth-child(3) > button.SAN-btn.trigger.info__share"
SHARE_DIALOG = "body > main > div > div.bottom.bot-scroll > div > div:nth-child(3) > div.SAN-panel.SAN-panel_context.dialog"
SHARE_DIALOG_CLOSE_BUTTON = "body > main > div > div.bottom.bot-scroll > div > div:nth-child(3) > div.SAN-panel.SAN-panel_context.dialog > div.top > svg"